[auth]
	# This is for the links a the bottom of login/join auth pages.
	or = "sau"
	join_link = "Înregistrează-te!"
	login_link = "Logează-te!"
	forgot_link = "Am uitat Porecla sau Parola"

# /login
[auth.login]
	page_title = "Logează-te în GameJolt"

	twitter_button = "Logează-te prin Twitter"
	facebook_button = "Logează-te prin Facebook"

	username_label = "Porecla"
	password_label = "Parola"
	submit_button = "Logează-te"

	# Shows up if you enter an invalid user/password combination.
	invalid_login_error_html = "Poreclă sau parolă incorectă."

	# Login takes a while, so we show this for the loading text.
	# Can be quirky and fun! =]
	loading_message_count = "4"
	loading_message_1 = "Conectare la calculatorul principal..."
	loading_message_2 = "Calculăm valoarea lui π..."
	loading_message_3 = "Pornim modulele de amuzament..."
	loading_message_4 = "Proiectăm matrixul hoopla..."

# /join
[auth.join]
	page_title = "Alăturăte în Game Jolt - Cea Mai Mare Colecție de Jocuri Indie Făcute de Oameni"

	twitter_button = "Înregistrează-te prin Twitter"
	facebook_button = "Înregistrează-te prin Facebook"

	# The lead text of the page.
	# Quirky and fun as it's the text to get them excited about signing up.
	# Let's try to keep it at 3 lines or less on the page.
	join_message_html_count = "2"
	join_message_html_1 = "Alăturăte nouă. Mwuahaha.<br>Noi avem jocuri.<br><strong><em>Mwuahahaha!</em></strong>"
	join_message_html_2 = "Alăturăte nouă pentru o calătorie cu racheta prin inima supernovei facută din jocuri."

	email_label = "Adresa de E-Mail"
	username_label = "Porecla"
	password_label = "Parola"

	submit_button = "Înregistrează-te"

# /join/almost
# After a successful sign up they land here.
# They still have to authorize their account.
[auth.join.almost]
	page_title = "Aproape gata!"
	heading = "@:auth.join.almost.page_title"
	body_html = """
	<p>Înainte de a te putea loga în Game Jolt, trebuie sa-ți verifici adresa de E-Mail de pe contul tău.</p>
	<p>Ți-am trimis un E-Mail cu intrucțiuni despre cum să-ți activezi contul.</p>
	"""
	spam = "Dacă nu vezi un E-Mail în zece minute, te-rog verifică fișierul pentru spam. Este posibil că acesta a ajuns acolo!"
	urgency = "Notă ca tu ai o săptămînă la dispoziție ca să îți activezi contul. După aceea, el va fi șters și va trebui să te înregistrezi din nou."

# You need to actually sign up to get a valid URL for this page.
# We only show a Growl on successful authorization and funnel off to the main site.
[auth.authorize]
	success_growl_title = "Cont Autorizat"
	success_growl = "Noi te re-direcționăm pe tine spre bordul tău Game Jolt acum."

# /authorize/169219/62b17036174c87ee503fe0ef2902c79d/2
# The page that shows when their authorization fails.
# They shouldn't get here unless they clicked the link again after authorizing. Or if they are trying to cheat something.
[auth.authorize.invalid]
	page_title = "Cod de Autorizație Invalid"
	heading = "Autorizație Invalidă"
	body_html = """
	<p>Codul tău de autorizație este invalid.</p>
	<p>Va-rog sa vă asigurați că copiați și depuneți întregul URL pe care vi l-am trimis.</p>
	"""

# /forgot
[auth.forgot]
	page_title = "Regăsire a Datelor de Logare"
	heading = "@:auth.forgot.page_title"

	email_help = "Depuneți adresa de E-Mail de pe contul vostru și vă vom trimite datele de logare prin E-Mail."
	email_label = "Adresa de E-Mail"
	submit_button = "Regăsirea Datelor"

	# If the email address they enter isn't a registered user, this shows up as an error message.
	invalid_email_error_html = """
	<p>Hmm, pare că această adresă de email nu este în sistemul nostru. Poate că nu<a href="/join">te-ai înregistrat încă?</a>?</p>
	"""

# /forgot/sent
# For after they fill out the "forgot" form.
[auth.forgot.sent]
	page_title = "Date Trimise"
	heading = "@:auth.forgot.sent.page_title"
	body_html = "<p>Ți-am trimis datele de logare spre adresa de E-Mail pe care ai depus-o.</p>"
	spam = "Dacă nu vezi un E-Mail în zece minute, te-rog verifică fișierul pentru spam. Este posibil că acesta a ajuns acolo!"

# The URL for this gets sent in an email when they fill out the forgot login credentials page.
[auth.reset_password]
	page_title = "Resetarea Parolei"
	heading = "@:auth.reset_password.page_title"

	password_help = "Dacă dorești să-ți resetezi parola, introdu una nouă dedesubt.If you'd like to reset your password, enter a new one below."
	password_label = "Parolă Nouă"
	submit_button = "Resetează Parola"

	# For when they successfully reset.
	# Will send them back to the login page after showing this Growl.
	success_growl_title = "Parolă Schimbată"
	success_growl = "Parola ta a fost resetată. Acum te poți loga cu cea nouă."


#####################
# Linked Account Auth

[auth.linked_account]

	# When they get returned back to GJ from FB/Twitter, etc. we do some processing of the login/sign up.
	# This is a generic loading message while we're doing our work.
	loading_message = "Procesăm. Vă-rog așteptați..."

[auth.linked_account.facebook]

	# Generic failed message.
	failed_growl = "Logare inaccesibilă prin Facebook."
	failed_growl_title = "Logare Nereușită"

	# For the rare case when FB doesn't give us an email address. This would be very rare if it did ever happen.
	no_email_growl = "Contul tău de Facebook nu a returnat nici o adresă de E-Mail. Asigurați-vă că ați verificat prin Facebook."
	no_email_growl_title = "O nu!"

	# When someone tries to sign up with an FB account with an email address that exists on an existing GJ account.
	# In most cases this will probably be an accident where they signed up in the past
	# and then try signing up again with FB later on, but their email address is
	# registered on their old account.
	duplicate_email_growl = "Adresa de E-Mail de pe acest cont Facebook este deja folosită. Poate că deja ai un cont?"
	duplicate_email_growl_title = "O nu!"

	# After a successful FB sign up.
	created_growl = "Contul tău a fost creat. De acum îl puteți folosi!"
	created_growl_title = "Cont Creat"

[auth.linked_account.twitter]

	# Generic failed message.
	failed_growl = "Logare inaccesibilă prin Twitter."
	failed_growl_title = "Logare nereușită"

	# When they submit the form and their account is set up with Twitter.
	created_growl = "Contul tău a fost creat. De acum îl puteți folosi!"
	created_growl_title = "Cont Creat"

# /login/finalize-twitter
# They get directed here when they sign up with a new twitter account and we require their email address.
[auth.linked_account.twitter.finalize]
	page_title = "E-Mail Necesar"
	heading = "@:auth.linked_account.twitter.finalize.page_title"

	email_help = "Ca să finisați logarea prin Twitter, introduceți o adresă de E-Mail validă."
	email_label = "Adresă de E-Mail"
	submit_button = "Completează Înregistrarea"

	# If they entered an email address that exists on another account.
	# In most cases this will probably be an accident where they signed up in the past
	# and then try signing up again with twitter later on, but their email address is
	# registered on their old account.
	duplicate_email_error_html = """
	<p>Adresa de E-Mail este deja folosită.</p>
	<p>Dacă deja aveți un cont Game Jolt, puteți să vă<a href="/login">logați aici</a>.</p>
	<p>Dacă ați uitat datele de logare, puteți să le<a href="/forgot">recuperați aici</a>.</p>
	"""
